JUMP_LINK(script_func_global_1),
JUMP_LINK(script_func_global_12),
JUMP_LINK(script_func_global_15),
JUMP_LINK(script_func_vo_thi),
LOAD_MODEL_FROM_GEO(MODEL_BUBBLY_TREE,     bubbly_tree_geo),
LOAD_MODEL_FROM_GEO(MODEL_thi_LEVEL_GEOMETRY_03,   thi_geo_0005F0),
LOAD_MODEL_FROM_GEO(MODEL_WARP_PIPE,       warp_pipe_geo),
