DEFINE_MODEL(MODEL_MARIO, mario,  mario_geo)
DEFINE_MODEL(MODEL_BUBBLY_TREE, tree,  bubbly_tree_geo)
DEFINE_MODEL(MODEL_COURTYARD_SPIKY_TREE, tree,  spiky_tree_geo)
DEFINE_MODEL(MODEL_SNOW_TREE, tree,  snow_tree_geo)
DEFINE_MODEL(MODEL_SSL_PALM_TREE, tree,  palm_tree_geo)
DEFINE_MODEL(MODEL_CASTLE_DOOR, door,  castle_door_geo)
DEFINE_MODEL(MODEL_WOODEN_DOOR, door,  wooden_door_geo)
DEFINE_MODEL(MODEL_BBH_HAUNTED_DOOR, door,  haunted_door_geo)
DEFINE_MODEL(MODEL_METAL_DOOR, door,  metal_door_geo)
DEFINE_MODEL(MODEL_HMC_HAZY_MAZE_DOOR, door,  hazy_maze_door_geo)
DEFINE_MODEL(MODEL_CASTLE_DOOR_0_STARS, door,  castle_door_0_star_geo)
DEFINE_MODEL(MODEL_CASTLE_DOOR_1_STAR, door,  castle_door_1_star_geo)
DEFINE_MODEL(MODEL_CASTLE_DOOR_3_STARS, door,  castle_door_3_stars_geo)
DEFINE_MODEL(MODEL_CASTLE_KEY_DOOR, door,  key_door_geo)
DEFINE_MODEL(MODEL_CCM_CABIN_DOOR, door,  cabin_door_geo)
DEFINE_MODEL(MODEL_DL_CANNON_LID, cannon_lid, cannon_lid_geo)
// DEFINE_MODEL(MODEL_BOWSER_2_TILTING_ARENA, _,  bowser_2_geo_000170)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_1, _,  bowser_3_geo_000290)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_2, _,  bowser_3_geo_0002A8)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_3, _,  bowser_3_geo_0002C0)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_4, _,  bowser_3_geo_0002D8)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_5, _,  bowser_3_geo_0002F0)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_6, _,  bowser_3_geo_000308)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_7, _,  bowser_3_geo_000320)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_8, _,  bowser_3_geo_000338)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_9, _,  bowser_3_geo_000350)
// DEFINE_MODEL(MODEL_BOWSER_3_FALLING_PLATFORM_10, _,  bowser_3_geo_000368)
DEFINE_MODEL(MODEL_BULLET_BILL, bullet_bill,  bullet_bill_geo)
DEFINE_MODEL(MODEL_YELLOW_SPHERE, yellow_sphere_small,  yellow_sphere_geo)
DEFINE_MODEL(MODEL_HOOT, hoot,  hoot_geo)
DEFINE_MODEL(MODEL_YOSHI_EGG, yoshi_egg,  yoshi_egg_geo)
DEFINE_MODEL(MODEL_THWOMP, thwomp,  thwomp_geo)
DEFINE_MODEL(MODEL_HEAVE_HO, heave_ho,  heave_ho_geo)
DEFINE_MODEL(MODEL_BLARGG, blargg,  blargg_geo)
DEFINE_MODEL(MODEL_BULLY, bully,  bully_geo)
DEFINE_MODEL(MODEL_BULLY_BOSS, bully,  bully_boss_geo)
DEFINE_MODEL(MODEL_WATER_BOMB, water_bubble,  water_bomb_geo)
DEFINE_MODEL(MODEL_WATER_BOMB_SHADOW, water_bubble,  water_bomb_shadow_geo)
DEFINE_MODEL(MODEL_KING_BOBOMB, king_bobomb,  king_bobomb_geo)
DEFINE_MODEL(MODEL_MANTA_RAY, manta,  manta_seg5_geo_05008D14)
DEFINE_MODEL(MODEL_UNAGI, unagi,  unagi_geo)
DEFINE_MODEL(MODEL_SUSHI, sushi,  sushi_geo)
DEFINE_MODEL(MODEL_CLAM_SHELL, clam_shell,  clam_shell_geo)
DEFINE_MODEL(MODEL_POKEY_HEAD, pokey,  pokey_head_geo)
DEFINE_MODEL(MODEL_POKEY_BODY_PART, pokey,  pokey_body_part_geo)
DEFINE_MODEL(MODEL_TWEESTER, tornado,  tweester_geo)
DEFINE_MODEL(MODEL_KLEPTO, klepto,  klepto_geo)
DEFINE_MODEL(MODEL_EYEROK_LEFT_HAND, eyerok,  eyerok_left_hand_geo)
DEFINE_MODEL(MODEL_EYEROK_RIGHT_HAND, eyerok,  eyerok_right_hand_geo)
DEFINE_MODEL(MODEL_MONTY_MOLE, monty_mole,  monty_mole_geo)
DEFINE_MODEL(MODEL_UKIKI, ukiki,  ukiki_geo)
DEFINE_MODEL(MODEL_FWOOSH, fwoosh,  fwoosh_geo)
DEFINE_MODEL(MODEL_SPINDRIFT, spindrift,  spindrift_geo)
DEFINE_MODEL(MODEL_MR_BLIZZARD_HIDDEN, snowman,  mr_blizzard_hidden_geo)
DEFINE_MODEL(MODEL_MR_BLIZZARD, snowman,  mr_blizzard_geo)
DEFINE_MODEL(MODEL_PENGUIN, penguin,  penguin_geo)
DEFINE_MODEL(MODEL_CAP_SWITCH, capswitch,  cap_switch_geo)
DEFINE_MODEL(MODEL_BOO, boo,  boo_geo)
DEFINE_MODEL(MODEL_BETA_BOO_KEY, small_key,  small_key_geo)
DEFINE_MODEL(MODEL_HAUNTED_CHAIR, chair,  haunted_chair_geo)
DEFINE_MODEL(MODEL_MAD_PIANO, mad_piano,  mad_piano_geo)
DEFINE_MODEL(MODEL_BOOKEND_PART, bookend,  bookend_part_geo)
DEFINE_MODEL(MODEL_BOOKEND, book,  bookend_geo)
DEFINE_MODEL(MODEL_HAUNTED_CAGE, haunted_cage,  haunted_cage_geo)
DEFINE_MODEL(MODEL_BIRDS, bird,  birds_geo)
DEFINE_MODEL(MODEL_YOSHI, yoshi,  yoshi_geo)
DEFINE_MODEL(MODEL_ENEMY_LAKITU, lakitu_enemy,  enemy_lakitu_geo)
DEFINE_MODEL(MODEL_SPINY_BALL, spiny_egg,  spiny_ball_geo)
DEFINE_MODEL(MODEL_SPINY, spiny,  spiny_geo)
DEFINE_MODEL(MODEL_WIGGLER_HEAD, wiggler_head,  wiggler_head_geo)
DEFINE_MODEL(MODEL_WIGGLER_BODY, wiggler_body,  wiggler_body_geo)
DEFINE_MODEL(MODEL_BUBBA, bubba,  bubba_geo)
DEFINE_MODEL(MODEL_BOWSER, bowser,  bowser_geo)
DEFINE_MODEL(MODEL_BOWSER_BOMB, bomb,  bowser_bomb_geo)
DEFINE_MODEL(MODEL_BOWSER_SMOKE, impact_smoke,  bowser_impact_smoke_geo)
DEFINE_MODEL(MODEL_BOWSER_FLAMES, bowser_flame,  bowser_flames_geo)
DEFINE_MODEL(MODEL_BOWSER_WAVE, impact_ring,  invisible_bowser_accessory_geo)
DEFINE_MODEL(MODEL_BOWSER_NO_SHADOW, bowser,  bowser_geo_no_shadow)
DEFINE_MODEL(MODEL_BUB, bub,  bub_geo)
DEFINE_MODEL(MODEL_TREASURE_CHEST_BASE, treasure_chest,  treasure_chest_base_geo)
DEFINE_MODEL(MODEL_TREASURE_CHEST_LID, treasure_chest,  treasure_chest_lid_geo)
DEFINE_MODEL(MODEL_CYAN_FISH, cyan_fish,  cyan_fish_geo)
DEFINE_MODEL(MODEL_WATER_RING, water_ring,  water_ring_geo)
DEFINE_MODEL(MODEL_SKEETER, skeeter,  skeeter_geo)
DEFINE_MODEL(MODEL_PIRANHA_PLANT, piranha_plant,  piranha_plant_geo)
DEFINE_MODEL(MODEL_WHOMP, whomp,  whomp_geo)
DEFINE_MODEL(MODEL_KOOPA_WITH_SHELL, koopa,  koopa_with_shell_geo)
DEFINE_MODEL(MODEL_METALLIC_BALL, chain_ball,  metallic_ball_geo)
DEFINE_MODEL(MODEL_CHAIN_CHOMP, chain_chomp,  chain_chomp_geo)
DEFINE_MODEL(MODEL_KOOPA_FLAG, koopa_flag,  koopa_flag_geo)
DEFINE_MODEL(MODEL_WOODEN_POST, poundable_pole,  wooden_post_geo)
DEFINE_MODEL(MODEL_MIPS, mips,  mips_geo)
DEFINE_MODEL(MODEL_BOO_CASTLE, boo_castle,  boo_castle_geo)
DEFINE_MODEL(MODEL_LAKITU, lakitu_cameraman,  lakitu_geo)
DEFINE_MODEL(MODEL_CHILL_BULLY, chillychief,  chilly_chief_geo)
DEFINE_MODEL(MODEL_BIG_CHILL_BULLY, chillychief,  chilly_chief_big_geo)
DEFINE_MODEL(MODEL_MONEYBAG, moneybag,  moneybag_geo)
DEFINE_MODEL(MODEL_SWOOP, swoop,  swoop_geo)
DEFINE_MODEL(MODEL_SCUTTLEBUG, scuttlebug,  scuttlebug_geo)
DEFINE_MODEL(MODEL_MR_I_IRIS, mr_i_iris,  mr_i_iris_geo)
DEFINE_MODEL(MODEL_MR_I_BODY, mr_i_eyeball,  mr_i_geo)
DEFINE_MODEL(MODEL_DORRIE, dorrie,  dorrie_geo)
DEFINE_MODEL(MODEL_YELLOW_COIN, coin,  yellow_coin_geo)
DEFINE_MODEL(MODEL_YELLOW_COIN_NO_SHADOW, coin,  yellow_coin_no_shadow_geo)
DEFINE_MODEL(MODEL_BLUE_COIN, coin,  blue_coin_geo)
DEFINE_MODEL(MODEL_BLUE_COIN_NO_SHADOW, coin,  blue_coin_no_shadow_geo)
DEFINE_MODEL(MODEL_HEART, heart,  heart_geo)
DEFINE_MODEL(MODEL_TRANSPARENT_STAR, transparent_star,  transparent_star_geo)
DEFINE_MODEL(MODEL_STAR, star,  star_geo)
DEFINE_MODEL(MODEL_WOODEN_SIGNPOST, wooden_signpost,  wooden_signpost_geo)
DEFINE_MODEL(MODEL_CANNON_BARREL, cannon_barrel,  cannon_barrel_geo)
DEFINE_MODEL(MODEL_CANNON_BASE, cannon_base,  cannon_base_geo)
DEFINE_MODEL(MODEL_BREAKABLE_BOX, breakable_box,  breakable_box_geo)
DEFINE_MODEL(MODEL_BREAKABLE_BOX_NO_SHADOW, breakable_box,  breakable_box_no_shadow_geo)
DEFINE_MODEL(MODEL_EXCLAMATION_BOX_OUTLINE, exclamation_box_outline,  exclamation_box_outline_geo)
DEFINE_MODEL(MODEL_MARIOS_WINGED_METAL_CAP, mario_cap,  marios_winged_metal_cap_geo)
DEFINE_MODEL(MODEL_MARIOS_METAL_CAP, mario_cap,  marios_metal_cap_geo)
DEFINE_MODEL(MODEL_MARIOS_WING_CAP, mario_cap,  marios_wing_cap_geo)
DEFINE_MODEL(MODEL_MARIOS_CAP, mario_cap,  marios_cap_geo)
DEFINE_MODEL(MODEL_EXCLAMATION_BOX, exclamation_box,  exclamation_box_geo)
DEFINE_MODEL(MODEL_DIRT_ANIMATION, dirt,  dirt_animation_geo)
DEFINE_MODEL(MODEL_CARTOON_STAR, dirt,  cartoon_star_geo)
DEFINE_MODEL(MODEL_BLUE_COIN_SWITCH, blue_coin_switch,  blue_coin_switch_geo)
DEFINE_MODEL(MODEL_MIST, mist,  mist_geo)
DEFINE_MODEL(MODEL_SPARKLES_ANIMATION, sparkle_animation,  sparkles_animation_geo)
// LOAD_MODEL_FROM_DL( MODEL_WHITE_PARTICLE_SMALL,    white_particle_small_dl,     LAYER_OCCLUDE_SILHOUETTE_ALPHA),
// LOAD_MODEL_FROM_GEO(MODEL_FISH_SHADOW,             fish_shadow_geo),
// LOAD_MODEL_FROM_DL( MODEL_SAND_DUST,               sand_seg3_dl_particle,       LAYER_OCCLUDE_SILHOUETTE_ALPHA),
// LOAD_MODEL_FROM_DL( MODEL_PEBBLE,                  pebble_seg3_dl_0301CB00,     LAYER_OCCLUDE_SILHOUETTE_ALPHA),
// LOAD_MODEL_FROM_DL( MODEL_WHITE_PARTICLE_DL,       white_particle_dl,           LAYER_OCCLUDE_SILHOUETTE_ALPHA),
DEFINE_MODEL(MODEL_RED_FLAME, flame,  red_flame_geo)
DEFINE_MODEL(MODEL_BLUE_FLAME, flame,  blue_flame_geo)
DEFINE_MODEL(MODEL_BURN_SMOKE, burn_smoke,  burn_smoke_geo)
DEFINE_MODEL(MODEL_SPARKLES, sparkle,  sparkles_geo)
DEFINE_MODEL(MODEL_SMOKE, walk_smoke,  smoke_geo)
DEFINE_MODEL(MODEL_WHITE_PARTICLE, white_particle,  white_particle_geo)
DEFINE_MODEL(MODEL_LEAVES, leaves,  leaves_geo)
DEFINE_MODEL(MODEL_WAVE_TRAIL, water_wave,  wave_trail_geo)
DEFINE_MODEL(MODEL_SMALL_WATER_SPLASH, small_water_splash,  small_water_splash_geo)
DEFINE_MODEL(MODEL_IDLE_WATER_WAVE, water_wave,  idle_water_wave_geo)
DEFINE_MODEL(MODEL_WATER_SPLASH, water_splash,  water_splash_geo)
DEFINE_MODEL(MODEL_BUBBLE, bubble,  bubble_geo)
DEFINE_MODEL(MODEL_PURPLE_MARBLE, bubble,  purple_marble_geo)
DEFINE_MODEL(MODEL_WATER_MINE, water_mine,  water_mine_geo)
DEFINE_MODEL(MODEL_BOWLING_BALL, bowling_ball,  bowling_ball_geo)
DEFINE_MODEL(MODEL_FISH, blue_fish,  fish_geo)
DEFINE_MODEL(MODEL_FISH_SHADOW, blue_fish,  fish_shadow_geo)
DEFINE_MODEL(MODEL_BUTTERFLY, butterfly,  butterfly_geo)
DEFINE_MODEL(MODEL_BLACK_BOBOMB, bobomb,  black_bobomb_geo)
DEFINE_MODEL(MODEL_KOOPA_SHELL, koopa_shell,  koopa_shell_geo)
DEFINE_MODEL(MODEL_KOOPA_WITHOUT_SHELL, koopa,  koopa_without_shell_geo)
DEFINE_MODEL(MODEL_GOOMBA, goomba,  goomba_geo)
DEFINE_MODEL(MODEL_SEAWEED, seaweed,  seaweed_geo)
DEFINE_MODEL(MODEL_AMP, amp,  dAmpGeo)
DEFINE_MODEL(MODEL_BOBOMB_BUDDY, bobomb,  bobomb_buddy_geo)
DEFINE_MODEL(MODEL_BOWSER_KEY_CUTSCENE, bowser_key,  bowser_key_cutscene_geo)
DEFINE_MODEL(MODEL_CHECKERBOARD_PLATFORM, checkerboard_platform,  checkerboard_platform_geo)
DEFINE_MODEL(MODEL_RED_FLAME_SHADOW, flame,  red_flame_shadow_geo)
DEFINE_MODEL(MODEL_BOWSER_KEY, bowser_key,  bowser_key_geo)
DEFINE_MODEL(MODEL_EXPLOSION, explosion,  explosion_geo)
DEFINE_MODEL(MODEL_SNUFIT, snufit,  snufit_geo)
DEFINE_MODEL(MODEL_PURPLE_SWITCH, purple_switch,  purple_switch_geo)
DEFINE_MODEL(MODEL_1UP, mushroom_1up,  mushroom_1up_geo)
DEFINE_MODEL(MODEL_RED_COIN, coin,  red_coin_geo)
DEFINE_MODEL(MODEL_RED_COIN_NO_SHADOW, coin,  red_coin_no_shadow_geo)
DEFINE_MODEL(MODEL_METAL_BOX, metal_box,  metal_box_geo)
DEFINE_MODEL(MODEL_NUMBER, number,  number_geo)
DEFINE_MODEL(MODEL_FLYGUY, flyguy,  flyguy_geo)
DEFINE_MODEL(MODEL_TOAD, toad,  toad_geo)
DEFINE_MODEL(MODEL_PEACH, peach,  peach_geo)
DEFINE_MODEL(MODEL_CHUCKYA, chuckya,  chuckya_geo)
DEFINE_MODEL(MODEL_WHITE_PUFF, mist,  white_puff_geo)
DEFINE_MODEL(MODEL_TRAJECTORY_MARKER_BALL, bowling_ball,  bowling_ball_track_geo)
// DEFINE_MODEL(MODEL_MAIN_MENU_MARIO_SAVE_BUTTON, _,  geo_menu_mario_save_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_RED_ERASE_BUTTON, _,  geo_menu_erase_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_BLUE_COPY_BUTTON, _,  geo_menu_copy_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_YELLOW_FILE_BUTTON, _,  geo_menu_file_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_GREEN_SCORE_BUTTON, _,  geo_menu_score_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_MARIO_SAVE_BUTTON_FADE, _,  geo_menu_mario_save_button_fade)
// DEFINE_MODEL(MODEL_MAIN_MENU_MARIO_NEW_BUTTON, _,  geo_menu_mario_new_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_MARIO_NEW_BUTTON_FADE, _,  geo_menu_mario_new_button_fade)
// DEFINE_MODEL(MODEL_MAIN_MENU_PURPLE_SOUND_BUTTON, _,  geo_menu_sound_button)
// DEFINE_MODEL(MODEL_MAIN_MENU_GENERIC_BUTTON, _,  geo_menu_generic_button)
DEFINE_MODEL(MODEL_WARP_PIPE, warp_pipe,  warp_pipe_geo)
#ifdef IA8_30FPS_COINS
DEFINE_MODEL(MODEL_SILVER_COIN, coin,  silver_coin_geo)
DEFINE_MODEL(MODEL_SILVER_COIN_NO_SHADOW, coin,  silver_coin_no_shadow_geo)
#endif
